
[loot]
	#Range: -100 ~ 100
	skill_book_mob_drop_chance_modifier = 0
	#Range: -100 ~ 100
	skill_book_chest_drop_chance_modifier = 0

[default_gamerule]
	hasFallAnimation = true
	globalStun = true
	canSwitchCombat = true
	#Range: 0 ~ 100
	weightPenalty = 100
	stiffComboAttacks = true
	noMobsInBossfight = true
	disapleEntityUI = false
	keepSkills = true
	doVanillaAttack = true

